[package]
name = "libwsclone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.23.0"
tracing = "0.1.37"
url = "2.3.1"
